name: frontend-deploy-scheduled

# 日本時間の8時, 17時に実行
on:
  schedule:
    - cron: '0 23 * * *' # 8時
    - cron: '0 8 * * *' # 17時

env:
  AWS_REGION: "us-east-1"
  IAM_ROLE_ARN: ${{ secrets.IAM_ROLE_ARN }}
  AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
  CF_DISTRIBUTION_ID: ${{ secrets.CF_DISTRIBUTION_ID }}

permissions:
  id-token: write
  contents: read

jobs:
  frontend_deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Setup dependencies
        run: bun install

      - name: Build
        run: bun run build
        working-directory: packages/frontend
        env:
          AWS_REGION: 'us-east-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TABLE_NAME: ${{ secrets.TABLE_NAME }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.IAM_ROLE_ARN}}

      - name: Upload files to S3 and Clear CF cache
        run: |
          aws s3 sync --exact-timestamps --delete ./packages/frontend/out s3://${{ env.AWS_BUCKET_NAME }}/
          aws cloudfront create-invalidation --distribution-id ${{ env.CF_DISTRIBUTION_ID }} --paths "/*"
